Support required property.
autofac/Autofac.Web pull request #16
Opened 2024-11-15 10:20 UTC by pengweiqhca

2024-11-17 14:06 UTC, alistairjevans commented
@pengweiqhca, I'm not sure I understand why the existing support for required property injection in Autofac 7+ doesn't cover this case? https://autofac.readthedocs.io/en/latest/register/prop-method-injection.html#required-properties

Can you explain?

2024-11-18 01:30 UTC, pengweiqhca commented
ASP.NET Web Forms only supports [property injection](https://github.com/autofac/Autofac.Web/blob/develop/src/Autofac.Integration.Web/Forms/DependencyInjectionModule.cs#L48).

2024-11-18 21:10 UTC, alistairjevans commented
Ah, of course, good point! Been a while since I've looked at the WebForms stuff.

2024-11-18 21:12 UTC, alistairjevans requested changes
Just a couple of points, thanks!

2024-11-18 21:12 UTC, alistairjevans commented on src/Autofac.Integration.Web/Forms/AttributedInjection.cs
> +    private static readonly ConcurrentDictionary<Type, bool> HasRequiredMemberAttributeCache =
Could you see if you can use the Autofac shared reflection cache? It allows caches to be invalidated per-assembly if required.

For example:

```
HasRequiredMemberAttributeCache = ReflectionCacheSet.Shared.GetOrCreateCache<ReflectionCacheDictionary<Type, bool>>("hasrequiredmemberattributecache");
```

This still gives you basically the same functionality, but we can centrally control it as needed.

2024-11-18 21:12 UTC, alistairjevans commented on src/Autofac.Integration.Web/Forms/AttributedInjection.cs
> +        return HasRequiredMemberAttributeCache.GetOrAdd(type, t =>
Can you please bring over the comment from Autofac to explain why we have to walk the tree?

```
// The RequiredMemberAttribute (may)* have Inherit = false on its AttributeUsage options,
// so walk the tree.
// (*): see `HasRequiredMemberAttribute` doc for why we dont really know much about the concrete attribute.
```

2024-11-18 21:12 UTC, alistairjevans commented on test/Autofac.Integration.Web.Test/Forms/AttributedInjectionModuleFixture.cs
> +        [Fact]
Can you please fix the indentation here?

2024-11-18 21:12 UTC, alistairjevans commented on test/Autofac.Integration.Web.Test/Forms/AttributedInjectionModuleFixture.cs
> +        private class RequiredMemberInjectedPage : HttpHandler
Indentation here too please.

2024-11-18 21:12 UTC, alistairjevans commented on src/Autofac.Integration.Web/ContainerProviderContainer.cs
> +    public object ResolveComponent(ResolveRequest request) => _containerProvider.RequestLifetime.ResolveComponent(request);
Why was this added?

2024-11-19 13:16 UTC, pengweiqhca commented on src/Autofac.Integration.Web/ContainerProviderContainer.cs
> +    public object ResolveComponent(ResolveRequest request) => _containerProvider.RequestLifetime.ResolveComponent(request);
Sorry, when I was modifying the code, I could not compile it and forgot to delete it after pulling the latest code.

2024-11-23 09:58 UTC, pengweiqhca commented
All things are resolved.

2024-12-02 21:16 UTC, alistairjevans approved these changes
Looks good, thanks, sorry for the delay.

2024-12-02 21:16 UTC, merged